language: csharp
os: linux
mono: none
sudo: required
dist: trusty

branches:
  only:
  - master

services:
  - docker

jobs:
  include:
    - stage: "Build / Test / Create image"
      script:
        # Build
        - docker build --target build .
        # Test
        - docker build --target test .
        - docker create --name travistest-test $(docker images --filter "label=travistest-test=true" -q | head -1)
        - docker cp travistest-test:/test-results ./test-results
        - cat ./test-results/test-results.xml
        # Create image
        - docker build -t travistest:1.0.0 .
