language: csharp
os: linux
mono: none
sudo: required
dist: trusty

branches:
  only:
  - master

services:
  - docker

jobs:
  include:
    # All stages are stuffed in a single script in order to reuse docker cache
    - stage: "Build / Test / Create image"
      script:
        # Build
        - docker build --target build .
        # Test
        - docker build --target test .
        - docker create --name travistest-test $(docker images --filter "label=travistest-test=true" -q | head -1)
        - docker cp travistest-test:/test-results ./test-results
        - cat ./test-results/test-results.xml
        # Create image
        - docker build -t travistest:1.0.0 .

# Multi-stage version - dotnet sdk image is pulled for each stage and job
#jobs:
#  include:
#    - stage: "Build"
#      script: docker build --target build .
#    - stage: "Test"
#      script: 
#        - docker build --target test .
#        - docker create --name travistest-test $(docker images --filter "label=travistest-test=true" -q | head -1)
#        - docker cp travistest-test:/test-results ./test-results
#        - cat ./test-results/test-results.xml
#    - stage: "Create image"
#      script: docker build -t travistest:1.0.0 .